###

# Listar Todos Usuários
GET http://localhost:8080/api/user

###

# Detalhes do usuário
GET http://localhost:8080/api/user/1

###

# Apagar
DELETE http://localhost:8080/api/user/2
Authorization: Basic admin@fiap.com.br administrador

###

# Cadastrar
POST http://localhost:8080/api/user
Content-Type: application/json

{
    "name": "Regina",
	"email": "regina@gmail.com",
	"password": "888555"
}

###

PUT http://localhost:8080/api/user/3
Content-Type: application/json
Authorization: Basic admin@fiap.com.br administrador

{
    "name": "Cleber",
	"email": "cleber@gmail.com"
}

###